//
//  Header.m
//  MoLi
//
//  Created by zhangbin on 12/20/14.
//  Copyright (c) 2014 zoombin. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NSString * const ML_UMENG_APP_KEY = @"54ac955bfd98c5cad600091b";

CGFloat const ML_COMMON_EDGE_LEFT = 15;
CGFloat const ML_COMMON_EDGE_RIGHT = ML_COMMON_EDGE_LEFT;
NSString * const ML_GOODS_PROPERTIES_PICKER_VIEW_STYLE_KEY = @"ML_GOODS_PROPERTIES_PICKER_VIEW_STYLE_KEY";

NSString * const ML_NOTIFICATION_IDENTIFIER_FETCH_STORE_COMMENTS = @"ML_NOTIFICATION_IDENTIFIER_FETCH_STORE_COMMENTS";
NSString * const ML_NOTIFICATION_IDENTIFIER_FETCH_STORE_DETAILS = @"ML_NOTIFICATION_IDENTIFIER_FETCH_STORE_DETAILS";
NSString * const ML_NOTIFICATION_IDENTIFIER_SYNC_CART = @"ML_NOTIFICATION_IDENTIFIER_SYNC_CART";
NSString * const ML_NOTIFICATION_IDENTIFIER_CLOSE_GOODS_PROPERTIES = @"ML_NOTIFICATION_IDENTIFIER_CLOSE_GOODS_PROPERTIES";
NSString * const ML_NOTIFICATION_IDENTIFIER_OPEN_GOODS_PROPERTIES = @"ML_NOTIFICATION_IDENTIFIER_OPEN_GOODS_PROPERTIES";
NSString * const ML_NOTIFICATION_IDENTIFIER_OPEN_ORDERS = @"ML_NOTIFICATION_IDENTIFIER_OPEN_ORDERS";
NSString * const ML_NOTIFICATION_IDENTIFIER_SIGNOUT = @"ML_NOTIFICATION_IDENTIFIER_SIGNOUT";
NSString * const ML_NOTIFICATION_IDENTIFIER_ADD_GOODS_TO_CART_SUCCEED = @"ML_NOTIFICATION_IDENTIFIER_ADD_GOODS_TO_CART_SUCCEED";
NSString * const ML_NOTIFICATION_IDENTIFIER_RED_DOT = @"ML_NOTIFICATION_IDENTIFIER_RED_DOT";
NSString * const ML_NOTIFICATION_IDENTIFIER_REFRESH_ORDER_DETAILS = @"ML_NOTIFICATION_IDENTIFIER_REFRESH_ORDER_DETAILS";

NSString * const ML_USER_DEFAULT_IDENTIFIER_NETWORKING = @"ML_USER_DEFAULT_IDENTIFIER_NETWORKING";
NSString * const ML_USER_DEFAULT_IDENTIFIER_PUSH = @"ML_USER_DEFAULT_IDENTIFIER_PUSH";
NSString * const ML_USER_DEFAULT_IDENTIFIER_PUSH_SOUND = @"ML_USER_DEFAULT_IDENTIFIER_PUSH_SOUND";
NSString * const ML_USER_DEFAULT_NETWORKING_VALUE_AUTO = @"ML_USER_DEFAULT_NETWORKING_VALUE_AUTO";
NSString * const ML_USER_DEFAULT_NETWORKING_VALUE_WIFI = @"WIFI";
NSString * const ML_USER_DEFAULT_NETWORKING_VALUE_3G = @"3G";
NSString * const ML_USER_DEFAULT_PUSH_NONE_VALUE = @"ML_USER_DEFAULT_PUSH_NONE_VALUE";
NSString * const ML_USER_DEFAULT_PUSH_VALUE = @"ML_USER_DEFAULT_PUSH_VALUE";
NSString * const ML_USER_DEFAULT_PUSH_SOUND_VALUE = @"ML_USER_DEFAULT_PUSH_SOUND_VALUE";
NSString * const ML_USER_DEFAULT_IDENTIFIER_DISPLAYED_GUIDE = @"ML_USER_DEFAULT_IDENTIFIER_DISPLAYED_GUIDE";
NSString * const ML_USER_DEFAULT_IDENTIFIER_NEXT_VERIFYCODE_TIMESTAMP = @"ML_USER_DEFAULT_IDENTIFIER_DISPLAYED_GUIDE";
NSString * const ML_USER_DEFAULT_IDENTIFIER_SEARCH_GOODS_HISTORY = @"ML_USER_DEFAULT_IDENTIFIER_SEARCH_HISTORY";
NSString * const ML_USER_DEFAULT_IDENTIFIER_SEARCH_STORES_HISTORY = @"ML_USER_DEFAULT_IDENTIFIER_SEARCH_STORES_HISTORY";
NSString * const ML_USER_DEFAULT_IDENTIFIER_ACCOUNT = @"ML_USER_DEFAULT_IDENTIFIER_ACCOUNT";
NSString * const ML_USER_DEFAULT_MAIN_VIEW_CONTROLLER_DATA_KEY = @"ML_USER_DEFAULT_MAIN_VIEW_CONTROLLER_DATA_KEY";
NSString * const ML_USER_DEFAULT_MAIN_VIEW_CONTROLLER_DATA_STYLE = @"ML_USER_DEFAULT_MAIN_VIEW_CONTROLLER_DATA_STYLE";
NSString * const ML_USER_DEFAULT_NEW_GOODS_COUNT_ADDED_TO_CART = @"ML_USER_DEFAULT_NEW_GOODS_COUNT_ADDED_TO_CART";

NSString * const ML_GOODS_TAKE = @"ML_GOODS_TAKE";

NSString * const ML_USER_NEWMESSAGETIME = @"ML_USER_NEWMESSAGETIME";

NSString * const ML_USER_NEWMESSAGELISTTIME = @"ML_USER_NEWMESSAGELISTTIME";

NSString * const ML_USER_UNREADMESSAGECOUNT = @"ML_USER_UNREADMESSAGECOUNT";
